# Generated by Django 5.2.5 on 2025-08-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_alter_quote_dislikes_alter_quote_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
