# Generated by Django 5.2.5 on 2025-08-26 11:09

from django.db import migrations


def create_initial_quotes(apps, schema_editor):
    Quote = apps.get_model('quotes_app', 'Quote')
    initial_quotes = [
        {"text": "Жизнь — это то, что с тобой происходит, пока ты строишь планы.", "source": "Джон Леннон", "weight": 5},
        {"text": "Счастье — это когда тебя понимают.", "source": "Альберт Эйнштейн", "weight": 10},
        {"text": "Неудача — это просто возможность начать снова, но уже более мудро.", "source": "Генри Форд", "weight": 4},
        {"text": "Только те, кто рискует слишком далеко, узнают, как далеко можно зайти.", "source": "Т.С. Элиот", "weight": 7},
        {"text": "Будущее принадлежит тем, кто верит в красоту своей мечты.", "source": "Элеонор Рузвельт", "weight": 3},
    ]
    for q in initial_quotes:
        Quote.objects.create(**q)

class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_alter_quote_dislikes_alter_quote_likes_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_quotes),
    ]
